### ISSUE TITLE
Batchnorm Fix

### ISSUE THREAD

**Issue by Wronskia** [tidsp/caffe-jacinto#13]
Hello Manu,

Do you think it would be possible for your team to fix this issue in caffe-jacinto?
https://github.com/NVIDIA/caffe/issues/436

**Comment by mathmanu** [comment]
Is this fixed in NVIDIA/caffe?

**Comment by Wronskia** [comment]
Hi,

No it is still not fixed. It will be fixed for the next release.
Best

**Comment by tianhemingheming** [comment]
when would the the next version be released?@Wronskia

**Comment by Wronskia** [comment]
@tianhemingheming I have no idea they did not give and expected time of arrival in the issue referenced above, I was wondering if it was possible for caffe-jacinto to make the fix before the next version release of NVcaffe

**Comment by Wronskia** [comment]
Hello @mathmanu 

The new version of NVcaffe  0.16.5 is now available.

Thanks a lot,
Best

**Comment by Wronskia** [comment]
Hello,

Is it possible to have an ETA for the integration of the new version of nvidia/caffe?

Thank you very much,
Best

**Comment by mathmanu** [comment]
A simple merge/rebase failed. We will have to manually look at the conflicts and resolve them. If you have an urgent need, I can try to do this by next friday.

**Comment by Wronskia** [comment]
Oh thanks a lot it would be amazing. 

Thank you again,
Best

**Comment by Wronskia** [comment]
Hello manu,

I am really sorry for the hassle, but do you think it would be possible to have it for next friday (26th)?

Thanks a lot and sorry again,
Best

**Comment by bonseyes-admin** [comment]
Hi,

NVIDIA caffe has released version 0.16.6 https://github.com/NVIDIA/caffe/releases/tag/v0.16.6 - how are you getting on upgrading to this release.

Thanks,
Tim

**Comment by mathmanu** [comment]
Hi, 

NVIDIA/caffe 0.17 is in he making with support for SSD object detection. 
You can follow the development and the PR that I submitted, here: https://github.com/NVIDIA/caffe/pull/446

I would like to merge after the above has been released.

Best regards,

**Comment by bonseyes-admin** [comment]
Hi, NVIDIA/caffe 0.17 is now released.
Thanks,

**Comment by bonseyes-admin** [comment]
Hi,

We are testing the NVIDIA Caffe 0.17 SSD implementation - we've found a couple of bugs and once these are resolved you should be able to merge : https://github.com/NVIDIA/caffe/issues/494

Thanks,

**Comment by mathmanu** [comment]
We have upgraded to caffe-0.17 branch now. Let us know if you find it useful.
